image: "mozilla/sbt:8u181_1.2.7"

stages:
  - test

test:
  stage: test
  script:
    - sbt clean coverage test coverageReport
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/scala-2.12/coverage-report/cobertura.xml
