name: RELEASE

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
  release:
    types: [published]
  

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.7]
        java: [adopt@1.8]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
            ~/.ivy2/cache
            ~/.coursier/cache/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Runs tests
        run: |
          sbt ++${{ matrix.scala }} test

  export-data:
    name: export chain data
    if: github.event_name != 'pull_request'
    needs: tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.7]
        java: [adopt@1.8]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
            ~/.ivy2/cache
            ~/.coursier/cache/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Build App
        run: |
          sbt ++${{ matrix.scala }} assembly

      - name: RUN Jar File release
        if: github.event_name == 'release'
        run: |
          ROSEN=$(find . -name 'contract-rosen-bridge-*.jar')
          java -jar $ROSEN tokens --type mainnet-alpha-1 --version ${{ github.event.release.tag_name }}
          java -jar $ROSEN contracts --network ergo --type mainnet-alpha-1 --version ${{ github.event.release.tag_name }}
          java -jar $ROSEN contracts --network cardano --type mainnet-alpha-1 --version ${{ github.event.release.tag_name }}

      - name: Upload JSON files
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release'
        with: 
          files: |
            contracts-*.json
            tokensMap-*.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        if: github.event_name != 'release'
        with:
          delete_release: true
          tag_name: Latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: RUN Jar File for push to master
        if: github.event_name != 'release'
        run: |
          ROSEN=$(find . -name 'contract-rosen-bridge-*.jar')
          java -jar $ROSEN tokens --type mainnet-alpha-1 --version Latest
          java -jar $ROSEN contracts --network ergo --type mainnet-alpha-1 --version Latest
          java -jar $ROSEN contracts --network cardano --type mainnet-alpha-1 --version Latest

      - name: Upload JSON files
        uses: softprops/action-gh-release@v1
        if: github.event_name != 'release'
        with: 
          tag_name: Latest
          files: |
            contracts-*.json
            tokensMap-*.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
